name: WEBAPP_PRODUCTION

on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  build-service:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@28fdb31ff34708d19615a74d67103ddc2ea9725c
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        

    - name: ServicePage 
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: client/webapp
        file: client/webapp/Dockerfile.development
        push: true
        tags: ${{ env.REMOTE_IMAGE }}
      env:
        REMOTE_IMAGE: ${{ secrets.DOCKER_USERNAME }}/remote:development